// Achievement definitions — checked after each run and on app start.
const List<Map<String, dynamic>> kAchievementDefs = [
  // Distance milestones
  {
    'id': 'first_run',
    'category': 'distance',
    'title': '初ラン',
    'description': '初めて走る',
    'condition': {'type': 'total_distance', 'value': 0.5},
    'rewardType': 'coins',
    'rewardValue': 100,
  },
  {
    'id': 'total_10km',
    'category': 'distance',
    'title': '10kmランナー',
    'description': '累計10km走破',
    'condition': {'type': 'total_distance', 'value': 10.0},
    'rewardType': 'coins',
    'rewardValue': 300,
  },
  {
    'id': 'total_50km',
    'category': 'distance',
    'title': '50kmランナー',
    'description': '累計50km走破',
    'condition': {'type': 'total_distance', 'value': 50.0},
    'rewardType': 'coins',
    'rewardValue': 500,
  },
  {
    'id': 'total_100km',
    'category': 'distance',
    'title': '100kmランナー',
    'description': '累計100km走破',
    'condition': {'type': 'total_distance', 'value': 100.0},
    'rewardType': 'coins',
    'rewardValue': 1000,
  },
  {
    'id': 'total_200km',
    'category': 'distance',
    'title': '200kmランナー',
    'description': '累計200km走破',
    'condition': {'type': 'total_distance', 'value': 200.0},
    'rewardType': 'coins',
    'rewardValue': 2000,
  },
  {
    'id': 'total_400km',
    'category': 'distance',
    'title': '400kmランナー',
    'description': '累計400km走破',
    'condition': {'type': 'total_distance', 'value': 400.0},
    'rewardType': 'coins',
    'rewardValue': 5000,
  },
  {
    'id': 'single_5km',
    'category': 'distance',
    'title': '5kmチャレンジ',
    'description': '1回で5km以上走る',
    'condition': {'type': 'single_distance', 'value': 5.0},
    'rewardType': 'coins',
    'rewardValue': 300,
  },
  {
    'id': 'single_10km',
    'category': 'distance',
    'title': '10kmチャレンジ',
    'description': '1回で10km以上走る',
    'condition': {'type': 'single_distance', 'value': 10.0},
    'rewardType': 'aura',
    'rewardValue': 'aura_sr_thunder',
  },

  // Level milestones
  {
    'id': 'reach_lv10',
    'category': 'level',
    'title': '進化の目覚め',
    'description': 'モンスターをLv10に育てる',
    'condition': {'type': 'level', 'value': 10},
    'rewardType': 'coins',
    'rewardValue': 500,
  },
  {
    'id': 'reach_lv20',
    'category': 'level',
    'title': '二段進化',
    'description': 'モンスターをLv20に育てる',
    'condition': {'type': 'level', 'value': 20},
    'rewardType': 'coins',
    'rewardValue': 1000,
  },
  {
    'id': 'reach_lv30',
    'category': 'level',
    'title': '三段進化',
    'description': 'モンスターをLv30に育てる',
    'condition': {'type': 'level', 'value': 30},
    'rewardType': 'coins',
    'rewardValue': 2000,
  },
  {
    'id': 'reach_lv40',
    'category': 'level',
    'title': '最終進化',
    'description': 'モンスターをLv40に育てる',
    'condition': {'type': 'level', 'value': 40},
    'rewardType': 'coins',
    'rewardValue': 3000,
  },
  {
    'id': 'reach_lv50',
    'category': 'level',
    'title': '伝説のランナー',
    'description': 'モンスターをLv50に育てる',
    'condition': {'type': 'level', 'value': 50},
    'rewardType': 'frame',
    'rewardValue': 'frame_sr_diamond',
  },

  // Gacha
  {
    'id': 'first_gacha',
    'category': 'gacha',
    'title': '初ガチャ',
    'description': '初めてガチャを引く',
    'condition': {'type': 'gacha_count', 'value': 1},
    'rewardType': 'coins',
    'rewardValue': 100,
  },
  {
    'id': 'gacha_10',
    'category': 'gacha',
    'title': 'ガチャ10回',
    'description': 'ガチャを10回引く',
    'condition': {'type': 'gacha_count', 'value': 10},
    'rewardType': 'coins',
    'rewardValue': 500,
  },
  {
    'id': 'gacha_50',
    'category': 'gacha',
    'title': 'ガチャ50回',
    'description': 'ガチャを50回引く',
    'condition': {'type': 'gacha_count', 'value': 50},
    'rewardType': 'banner',
    'rewardValue': 'banner_sr_legend',
  },

  // Streak
  {
    'id': 'streak_3',
    'category': 'streak',
    'title': '3日連続ラン',
    'description': '3日連続で走る',
    'condition': {'type': 'streak', 'value': 3},
    'rewardType': 'coins',
    'rewardValue': 300,
  },
  {
    'id': 'streak_7',
    'category': 'streak',
    'title': '1週間連続ラン',
    'description': '7日連続で走る',
    'condition': {'type': 'streak', 'value': 7},
    'rewardType': 'coins',
    'rewardValue': 1000,
  },
  {
    'id': 'streak_30',
    'category': 'streak',
    'title': '1ヶ月連続ラン',
    'description': '30日連続で走る',
    'condition': {'type': 'streak', 'value': 30},
    'rewardType': 'aura',
    'rewardValue': 'aura_ssr_rainbow',
  },
];
